name: Steward

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  steward:
    runs-on: ubuntu-latest
    name: Steward
    steps:
      - uses: actions/checkout@v3

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: 207632
          private_key: ${{ secrets.STEWARD_SECRET }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          repos-file: 'repos.md'
          author-email: 207632+nt9-steward[bot]@users.noreply.github.com
          author-name: nt9-steward[bot]
          github-app-id: 207632
          github-app-key: ${{ secrets.STEWARD_SECRET }}
